### ISSUE TITLE
PackageNotFoundError: conda install on Windows

### ISSUE THREAD

**Issue by singh-abhijeet** [maciejkula/spotlight#102]
Thanks guys for developing (and open-sourcing) a PyTorch based Recommender Engine. We are interested to leverage it in one of our project.

While trying to install the package using `conda` on Windows, am getting `PackageNotFoundError: Packages missing in current channels`. Seems like the selected conda channel (maciejkula, pytorch) does not have the required packages (spotlight 0.1.4).

Has the channel changed? Do you guys support `pip` based install? If yes, would request to add `pip` based installation steps on GitHub's landing page (README.md).

**Full trace:**
```java
(py3.6) C:\Users\Abhijeets>conda install -c maciejkula -c pytorch spotlight=0.1.4
Fetching package metadata .................
Solving package specifications:

PackageNotFoundError: Packages missing in current channels:

  - spotlight 0.1.4* -> pytorch 0.3.1.*

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/maciejkula/win-64
  - https://conda.anaconda.org/maciejkula/noarch
  - https://conda.anaconda.org/pytorch/win-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch

**Comment by maciejkula** [comment]
On Windows, you need to use `conda install -c maciejkula -c pytorch -c peterjc123 spotlight=0.1.4` as per https://github.com/maciejkula/spotlight/pull/98/files

**Comment by singh-abhijeet** [comment]
Thanks @maciejkula . Please add this as a caveat on GitHub page (README.md).
