### ISSUE TITLE
question about context_feature in the hybrid branch

### ISSUE THREAD

**Issue by nianjihouzz** [maciejkula/spotlight#104]
checkout your `hybrid_models` branch and noticed you are implementing a context_feature in addition to user_feature, item_feature to handle meta_data. Can you please elaborate on what "context_feature" is in your mind ?
Also from your hybrid network, it looks like, metadata embedding is added to id_embedding, based your experience, have you tried other ways to combine these embeddings (e.g. concatenate(user_id_emb, user_feature).dot(concatenate(item_id_emb, item_feature)) + bias_terms)
```
        if self.user is not None:
            user_representation += self.user(user_features)
        if self.context is not None:
            user_representation += self.context(context_features)
        if self.item is not None:
            item_representation += self.item(item_features)
```
Thanks

**Comment by maciejkula** [comment]
Things like: date, time of day, location on the website: things that are neither user nor item features.

I haven't really tried a lot of things, but [this](https://research.google.com/pubs/pub46488.html) suggests that using multiplication for context might be useful.
