### ISSUE TITLE
I ran this command but met problems

### ISSUE THREAD

**Issue by swan815** [maciejkula/spotlight#106]
I ran this command:conda install -c maciejkula -c pytorch -c peterjc123 spotlight=0.1.4
but showed the error  
conda install -c maciejkula -c pytorch -c peterjc123 spotlight=0.1.3
Fetching package metadata ...........
Solving package specifications: 

PackageNotFoundError: Packages missing in current channels:
            
  - spotlight 0.1.3* -> pytorch 0.3.0 -> mkl >=2018

**Comment by maciejkula** [comment]
What Python version? Which operating system?

**Comment by swan815** [comment]
python 2.7 
macOS Sierra 10.12.6

**Comment by swan815** [comment]
the terminal shows that
conda install -c maciejkula -c pytorch -c peterjc123 spotlight=0.1.3
Fetching package metadata ...........
Solving package specifications: 

PackageNotFoundError: Packages missing in current channels:
            
  - spotlight 0.1.3* -> pytorch 0.3.0 -> mkl >=2018

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/maciejkula/osx-64
  - https://conda.anaconda.org/maciejkula/noarch
  - https://conda.anaconda.org/pytorch/osx-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://conda.anaconda.org/peterjc123/osx-64
  - https://conda.anaconda.org/peterjc123/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch

**Comment by maciejkula** [comment]
It looks like you have actually ran an installation command for Spotlight 0.1.3 instead of 0.1.4?

Try
```
conda install -c maciejkula -c pytorch -c peterjc123 spotlight=0.1.4
```
as per [the installation instructions](https://github.com/maciejkula/spotlight/).

**Comment by maciejkula** [comment]
Also, please learn how to format code on Github: https://guides.github.com/features/mastering-markdown/#

**Comment by swan815** [comment]
Sorry for the format
 `conda install -c maciejkula -c pytorch -c peterjc123 spotlight=0.1.4
Fetching package metadata ...
........
Solving package specifications: 

PackageNotFoundError: Packages missing in current channels:
            
  - spotlight 0.1.4* -> pytorch 0.3.1.* -> mkl >=2018

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/maciejkula/osx-64
  - https://conda.anaconda.org/maciejkula/noarch
  - https://conda.anaconda.org/pytorch/osx-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://conda.anaconda.org/peterjc123/osx-64
  - https://conda.anaconda.org/peterjc123/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch`
I tried 0.1.4, but showed the same problem.

**Comment by swan815** [comment]
Sorry for the format. I ignored that.
```
conda install -c maciejkula -c pytorch -c peterjc123 spotlight=0.1.4
Fetching package metadata ...
........
Solving package specifications:

PackageNotFoundError: Packages missing in current channels:

spotlight 0.1.4* -> pytorch 0.3.1.* -> mkl >=2018
We have searched for the packages in the following channels:

https://conda.anaconda.org/maciejkula/osx-64
https://conda.anaconda.org/maciejkula/noarch
https://conda.anaconda.org/pytorch/osx-64
https://conda.anaconda.org/pytorch/noarch
https://conda.anaconda.org/peterjc123/osx-64
https://conda.anaconda.org/peterjc123/noarch
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-64
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
```
I tried 0.1.4, but showed the same problem.

**Comment by maciejkula** [comment]
Maybe the tsinghua Fonda mirror doesn't have the right packages? Can you
try not using the mirror?

**Comment by mszep** [comment]
FWIW, I'm getting the same thing. Python 3.6.2 (miniconda) on fedora 27

```
marks@localhost ~/d/n/m/r/model_testing> conda install -c maciejkula -c pytorch -c peterjc123 spotlight=0.1.4                                                         (usecases) 
Fetching package metadata ...............
Solving package specifications: 

PackageNotFoundError: Packages missing in current channels:
            
  - spotlight 0.1.4* -> pytorch 0.3.1.* -> mkl >=2018
  - spotlight 0.1.4* -> pytorch 0.3.1.* -> cudnn 7.0.*

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/maciejkula/linux-64
  - https://conda.anaconda.org/maciejkula/noarch
  - https://conda.anaconda.org/pytorch/linux-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://conda.anaconda.org/peterjc123/linux-64
  - https://conda.anaconda.org/peterjc123/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
            

marks@localhost ~/d/n/m/r/model_testing> python --version                                                                                                             (usecases) 
Python 3.6.2 :: Continuum Analytics, Inc.
marks@localhost ~/d/n/m/r/model_testing>    ```

No change even after installing latest pytorch release following instructions on pytorch.org.

**Comment by maciejkula** [comment]
I made a [separate repo](https://github.com/maciejkula/spotlight-installation-test) with a [CI build](https://travis-ci.org/maciejkula/spotlight-installation-test) to reproduce this, but everything looks fine. Can you have a look at the [installation script](https://github.com/maciejkula/spotlight-installation-test/blob/master/.travis/install.sh) and see if that gives you a hint as to what is wrong?

**Comment by mszep** [comment]
Interesting; given that a freshly installed conda works, I tried doing `conda update conda` (outside of any environment) and that resolved the issue. Perhaps one of the other channels relies on a new feature of conda or something?

On a related note, would you accept a PR which would enable users to install with pip as well? Or is that not feasible due to dependencies like CuDNN or MKL?

**Comment by maciejkula** [comment]
Sure, let's try making it work with pip. I think PyTorch used to be only available on conda, but seeing as it's now on pip as well there is no reason Spotlight shouldn't be.

**Comment by maciejkula** [comment]
Closing now but happy to re-open for pip uploading.
