### ISSUE TITLE
Multiple Criteria Recommendation Support

### ISSUE THREAD

**Issue by andre-motta** [maciejkula/spotlight#119]
I didn't understand through the documentation and by reading the code. 
Does spotlight support Multiple Criteria Decision Making 

For example in the factorization module, can the rating be a vector and therefore the object would be a matrix? Or is that something that i'd have to implement on my own?

Been looking to step away from ML.NET now that finally my project allows for me to develop a unique machine learning module.

Thanks in advance!

**Comment by maciejkula** [comment]
No, this is not implemented.

**Comment by andre-motta** [comment]
Thank you for your response!
