### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by blancyin** [maciejkula/spotlight#13]
When i try to import some modules:

from spotlight.datasets.movielens import get_movielens_dataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'spotlight.datasets'

from spotlight.factorization.explicit import ExplicitFactorizationModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'spotlight.factorization'

**Comment by blancyin** [comment]
from spotlight.cross_validation import random_train_test_split
from spotlight.evaluation import rmse_score
Parts are all right.

**Comment by maciejkula** [comment]
How did you install the package? Are the modules present on the filesystem?

**Comment by blancyin** [comment]
I tried to use conda and cloning the package to install,  meet the same problem.
I can run test code in spotlight-master file.
Waiting for the official release.

**Comment by maciejkula** [comment]
Can you:
1. Uninstall what you have at the moment.
2. Clone the package.
3. Go into the package directory.
4. Run `pip install -e .`.

This _ought to_ work.

**Comment by blancyin** [comment]
It worked.
Thank you for your help.
