### ISSUE TITLE
Cannot install spotlight via pip

### ISSUE THREAD

**Issue by mexangel** [maciejkula/spotlight#130]
Hi,

I am using an environment where conda install is not possible. I have tried installing via pip but it doesn't work. Has anyone tried this? Would appreciate any tips.

**Comment by huyhoang17** [comment]
change directory inside the root folder of project then: `pip install .`

**Comment by artdgn** [comment]
@mexangel I think you can also use `pip install git+https://github.com/maciejkula/spotlight.git@master#egg=spotlight` as a single command (or add it to the `requirements.txt` of your project, if you're trying to automate it)

**Comment by maciejkula** [comment]
Thanks for your help, @artdgn!

**Comment by mexangel** [comment]
NB: https://github.com/maciejkula/spotlight.git@master#egg=spotlight doesn't exist

**Comment by chrisjune** [comment]
> @mexangel I think you can also use `pip install git+https://github.com/maciejkula/spotlight.git@master#egg=spotlight` as a single command (or add it to the `requirements.txt` of your project, if you're trying to automate it)

It helped a lot!
