### ISSUE TITLE
How to predict items for a particular user ?

### ISSUE THREAD

**Issue by mohammad1234** [maciejkula/spotlight#21]
As far as i understand the model can predict a sequence of items for a given item/items in sequence, but how to get personalized predictions for a given user? 

Is it possible to extract the learned user embeddings or item embeddings from the model which can be used to generate a predicted weight by doing a dot product?

**Comment by hadi-gharibi** [comment]
as much as i know,they use this kind of models bcz of lake of data(users clicks are highly sparse) or for kind of data with high freshness needed (classifieds websites) ,so instead of pay attention to how ONE user interact with system,they assume that can model the user with this sequence of items that clicked by user.

**Comment by maciejkula** [comment]
@hadi-gharibi is exactly right: in [sequence](https://maciejkula.github.io/spotlight/sequence/representations.html) models, the user _is_ the sequence of past items they have clicked.

If you're looking to extract representations for users and items that you can then just multiply together, you can:

1. Use the [user_representation](https://maciejkula.github.io/spotlight/sequence/representations.html#spotlight.sequence.representations.CNNNet.user_representation) methods of the sequence model to get the user representation (you can access them via the `._net` attribute on the fitted models).
2. Use the `item_embeddings` attribute on the representations to get out the item embedding vectors.

**Comment by mohammad1234** [comment]
@maciejkula ... Thanks ... i'll try out the methods.

**Comment by EvaristeleDuellist** [comment]
@mohammad1234 Could you get to predict the personalized recommentadions for a given user. I am kind of stuck. Thanks
