### ISSUE TITLE
Cannot pass in optimizer to models

### ISSUE THREAD

**Issue by EthanRosenthal** [maciejkula/spotlight#22]
Because the representations (i.e. classes that inherit from `torch.nn.Module`) are instantiated inside of the `fit` method for the models, it is impossible to pass in an instance of a PyTorch optimizer because one would need to already know the module parameters beforehand.

Perhaps one should pass in a string (e.g. 'sgd') and then that gets mapped to PyTorch optimizers? Or, one can pass in a reference to the optimizer class that then gets instantiated with the module parameters.

**Comment by maciejkula** [comment]
Yes, this is absolutely broken. A couple of options:

1. Class to be instantiated.
2. String, as you suggest. I think I prefer this option.
3. A function that takes in the parameters as an arg and returns an optimizer.

I'll mull it over; I will also accept PRs. This is relatively orthogonal to the stuff I'm actively working on, so should be eminently mergeable. For now I stuck it in [trello](https://trello.com/c/JWVh2Wq0/8-fix-passing-in-optimizers)

**Comment by EthanRosenthal** [comment]
I like option 3 the best. With option 2, spotlight would have to be kept in sync with PyTorch developments if new optimizers are introduced, and this seems painful.

I took a stab at implementing this in a [PR](https://github.com/maciejkula/spotlight/pull/23)

**Comment by maciejkula** [comment]
Agreed. Thanks for the PR!
