### ISSUE TITLE
releases/download not available

### ISSUE THREAD

**Issue by mafeko** [maciejkula/spotlight#27]
Hi, 

I manually downloaded your stable 0.1.1 but with the example code from [here](https://github.com/maciejkula/spotlight/tree/master/examples/movielens_explicit) I get this error.

HTTPError: 404 Client Error: Not Found for url: https://github.com/maciejkula/recommender_datasets/releases/download/0.1.0%5Cmovielens_100K.hdf5

Seems that the whole "releases" folder isn't present anymore.

Thanks for your help !

**Comment by maciejkula** [comment]
It looks like Github (where the data is hosted) is having problems. The problem will resolve itself once Github is operational again.

**Comment by maciejkula** [comment]
Github is back, so you should have no more problems.

**Comment by mafeko** [comment]
Thanks  👍  !
