### ISSUE TITLE
'weights' paramter

### ISSUE THREAD

**Issue by nonamestreet** [maciejkula/spotlight#33]
Does the "weights" parameter of Interactions class mean the weight for a specific interaction?
It seems to me that the parameter was not used in any place.

**Comment by maciejkula** [comment]
This is correct, the implementation is still missing (but is tracked on [trello](https://trello.com/c/ePxmDAsT/11-wire-in-observation-weights)).

I will get round to it, but will be very happy to accept PRs in the meantime.

**Comment by maciejkula** [comment]
https://github.com/maciejkula/spotlight/issues/40

**Comment by nonamestreet** [comment]
Thank you!!!
