### ISSUE TITLE
Negative sampling

### ISSUE THREAD

**Issue by nonamestreet** [maciejkula/spotlight#36]
@maciejkula I guess we should remove the items found the training dataset before the negative sampling. Otherwise, it might make the learning less effective?

**Comment by maciejkula** [comment]
For implicit models, the only user-item pairs your dataset should contain are those where an interaction has been observed. You should not include pairs where an interaction is missing. Does this answer your question?

**Comment by nonamestreet** [comment]
Thank you for the reply. The negative sampling part of the code was sampling from all items. I guess this should exclude the observed interactions, as they are definitely not negative.

``` Python
 
    def _get_negative_prediction(self, user_ids):

        negative_items = sample_items(
            self._num_items,
            len(user_ids),
            random_state=self._random_state)
        negative_var = Variable(
            gpu(torch.from_numpy(negative_items), self._use_cuda)
        )
        negative_prediction = self._net(user_ids, negative_var)

        return negative_prediction

```

**Comment by maciejkula** [comment]
In principle you are right. In practice, as long as the number of all items is (much) larger than the number of positive items (which is usually the case), I haven't found this omission detrimental to accuracy. I suspect that you could even make the argument that this approach gives you an implicit regularizer.

**Comment by nonamestreet** [comment]
Yeah, I agree. It can only be a potential problem when the number of items is small. Thank you!

**Comment by KylinA1** [comment]
> In principle you are right. In practice, as long as the number of all items is (much) larger than the number of positive items (which is usually the case), I haven't found this omission detrimental to accuracy. I suspect that you could even make the argument that this approach gives you an implicit regularizer.

Hi, I try both, and I find this sampling significantly reduce the performance.

**Comment by KylinA1** [comment]
> > In principle you are right. In practice, as long as the number of all items is (much) larger than the number of positive items (which is usually the case), I haven't found this omission detrimental to accuracy. I suspect that you could even make the argument that this approach gives you an implicit regularizer.
> 
> Hi, I try both on MovieLens 1M dataset, and I find this sampling significantly reduce the performance.
