### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by navacron** [maciejkula/spotlight#61]
Using python 3.6 in conda environment. Getting the following error 

conda install -c maciejkula -c soumith spotlight=0.1.2
Fetching package metadata .............

PackageNotFoundError: Package missing in current osx-64 channels:
  - spotlight 0.1.2*

**Comment by maciejkula** [comment]
Sorry about that. I haven't pushed 0.1.2 to the conda channels yet. You can
clone this repository or install 0.1.1 from Conda. I'll get the new version
uploaded on the next couple of days.

**Comment by navacron** [comment]
Hi Maciej,

Thanks, that worked!

Thanks for the package. I am interested in prototyping news recommendation,
using webstream and content data. Would youtube, or lstm models be a good
choice, and have you tested using any open source web data?

Regards

**Comment by maciejkula** [comment]
The LSTM models should be a good fit.

I'm still working on a nice way of integrating content data into the models; I imagine that would be crucial for news recommendations.

**Comment by navacron** [comment]
Hi Again,

I am going through the code and understand how its implemented.

In sequence/representations.py line 193

self.lstm = nn.LSTM(batch_first=True,
                    input_size=embedding_dim,
                    hidden_size=embedding_dim)


I do not understand how the LSTM is being used. It is not referenced in the
forward function. Also CNNNet, LSTMNet, PoolNet have the same
implementation for forward methods.

Is this code still work in progress, or am I missing something?

Regards

**Comment by maciejkula** [comment]
The key differences are in the [`user_representation` functions](https://github.com/maciejkula/spotlight/blob/master/spotlight/sequence/representations.py#L197). These feed into the `forward` methods.
