### ISSUE TITLE
Clarity on documentation

### ISSUE THREAD

**Issue by nahidalam** [maciejkula/spotlight#65]
Hi

I am using spotlight with movieLens dataset to build a simple recommender system. Finding it hard to understand what some of the functions actually returns?

For example - 

`mrr = mrr_score(model, test)`

The documentation says "`One score is given for every user with interactions in the test set`". What does this score means? Is it predicting something?

When I print the result, I get

```
MRR Score
[ 0.04613095  0.01775374  0.02144497 ...,  0.00335534  0.04208428 0.01965703]
```

Also, what does `model.predict(user_id)` predicts?

Again when I print, I get below results:
```

User 3
[-21.33734512  22.07717514  12.95882034 ..., -13.99704361 -10.88421345 5.03288126]
```

**Comment by maciejkula** [comment]
As per the [documentation](https://maciejkula.github.io/spotlight/factorization/implicit.html#spotlight.factorization.implicit.ImplicitFactorizationModel.predict), the models output recommendation scores for user-item pairs. The `mrr_score` function outputs mean reciprocal rank scores (as per the [documentation](https://maciejkula.github.io/spotlight/evaluation.html#spotlight.evaluation.mrr_score)).

Is there something that's not in the docs that could be clarified?

**Comment by nahidalam** [comment]
@maciejkula Thanks, I have seen those earlier. What is not clear to me is how to interpret the results. For example, if `model.predict(user_id)` outputs a negative number, does that mean the model will rank that movie lower than if the output were a positive number?

Similarly, for `mrr_score` I understand it outputs mean reciprocal rank scores. But beyond the math, is it predicting something?

**Comment by maciejkula** [comment]
The higher the score, the stronger the recommendation (within the context of one user's ranking), so (as you say) negative numbers are worse than positive numbers.

For the MRR scores: it's ranking every item for a given user, the computing the MRR of the positive items in the test set. In that sense, it is constructing a ranking for each user (making predictions) and then computing the performance metric.
