### ISSUE TITLE
Roadmap: Hybrid Recommender?

### ISSUE THREAD

**Issue by RAbraham** [maciejkula/spotlight#79]
Hi,
I was looking at LightFM and saw item and user metadata being used for recommendations. This is really cool. Just wondering if such functionality is in the roadmap for `spotlight`?

**Comment by maciejkula** [comment]
You can do this right now by constructing your representation layers in the right way.

For example, you can create an item representation layer that stores item metadata, then use the item indices passed into it during training to retrieve the metadata and return its representation as part of the item representation.

For example, you could write something like this:
```
class FeatureLayer(nn.Module):

    def __init__(self, features, hidden_dim=32):

        super(FeatureLayer, self).__init__()

        self._hidden_dim = hidden_dim
        self._feature_dim = features.shape[1]
        self._features = Variable(torch.from_numpy(features.astype(np.float32)))
        self._hidden = nn.Linear(self._feature_dim, self._hidden_dim)

    def forward(self, item_indices):

        batch_size, sequence_length = item_indices.size()

        # Flatten the indices
        features = self._features[item_indices.resize(batch_size * sequence_length)]

        # Apply any transformation layers
        features = self._hidden(features)

        # Reshape again into (minibatch, sequence, embedding)
        features = features.resize(batch_size, sequence_length, self._hidden_dim)

        return features
```

**Comment by RAbraham** [comment]
This is great. Thanks!

**Comment by nikisix** [comment]
@maciejkula Think it might be worth throwing some logic around this idea? Might be a good way to help the sequence models with cold-starting right?

**Comment by sgaseretto** [comment]
How could this be applied to sequence models like the causal convolutional network?
