### ISSUE TITLE
Unit tests on Windows

### ISSUE THREAD

**Issue by rth** [maciejkula/spotlight#82]
When running the tests suite of the master branch on Windows 10, multiple tests currently fail,
```
pytest -sv tests/
[...]
=============== 34 failed, 24 passed, 3 error in 24.89 seconds ================
```
full output can be found [here](https://github.com/maciejkula/spotlight/files/1597597/spotlight_tests.txt). 

Two most frequent errors are,
 - [ ] ValueError in `randint`
   ```
    ..\spotlight\cross_validation.py:146: in user_based_train_test_split
        seed = random_state.randint(minint, maxint)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    >   ???
    E   ValueError: high is out of bounds for int32

    mtrand.pyx:975: ValueError
    ```
 - [ ] and dtype mismatch in `torch.index_select`,
    ```
        def _get_hashed_indices(self, original_indices):
            # [...]
            hashed_indices = torch.index_select(self._hashes,
                                                0,
    >                                           original_indices.squeeze())
    E       TypeError: torch.index_select received an invalid combination of arguments - got (torch.LongTensor, int, !torch.IntTensor!), but expected (torch.LongTensor source, int dim, torch.LongTensor index)

    ..\spotlight\layers.py:204: TypeError
    ```

Run on the master branch with the following installed depedencies,
```py
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import sklearn; print("Scikit-Learn", sklearn.__version__)
import torch; print("PyTorch", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)
import spotlight; print("spotlight", spotlight.__version__)
```

```
Windows-10-10.0.14393-SP0
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)]
NumPy 1.12.1
SciPy 1.0.0
Scikit-Learn 0.19.1
PyTorch 0.3.0b0+591e73e
CUDA available: True
CUDA version: 8.0
spotlight v0.1.3
```
PyTorch for Windows was installed from  the `peterjc123` conda channel, as described in https://github.com/pytorch/pytorch/issues/494#issuecomment-304439658

When installed on Linux with the same approach (though without GPU support), all tests pass.

**Comment by rth** [comment]
First issue appears to be due to the fact that `np.random.randint`, [has by default `dtype='l'`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.random.randint.html) while long is going to 32 bit not 64 bit on Windows.

Second issue is that embedding input somehow ends up being `IntTensor` instead of `LongTensor` which fails in PyTorch due to https://github.com/pytorch/pytorch/issues/145

**Comment by maciejkula** [comment]
Thank you for the reports. I started work on them in https://github.com/maciejkula/spotlight/pull/84, adding Windows CI for good measure.
