### ISSUE TITLE
besides bpr

### ISSUE THREAD

**Issue by arita37** [maciejkula/spotlight#88]
Just womdering technical hurddles
for warp loss.

**Comment by maciejkula** [comment]
There is the [adaptive hinge loss](https://maciejkula.github.io/spotlight/losses.html?highlight=losses#spotlight.losses.adaptive_hinge_loss) which is very similar to WARP, and consistently produces better accuracy than BPR in all my experiments. It is what I recommend using.

**Comment by arita37** [comment]
Noted, thx.
Have you seen the paper GAN for IR ?
https://arxiv.org/abs/1705.10513

Looks like improvement of negative sampling, using more specific Proba.






On Jan 9, 2018, at 7:55, Maciej Kula <notifications@github.com> wrote:

There is the adaptive hinge loss which is very similar to WARP, and consistently produces better accuracy than BPR in all my experiments. It is what I recommend using.

―

**Comment by nianjihouzz** [comment]
Just curious, if the adaptive negative sampling can be generally to applied to other pair-wise loss say bpr other than hinge loss ? thanks. @maciejkula

**Comment by maciejkula** [comment]
@arita37 yes, I have seen it. It looks very interesting but I haven't had time to implement it.

@nianjihouzz I think that's correct, but it's not implemented.
