### ISSUE TITLE
Conda Install Issue (Windows 10)

### ISSUE THREAD

**Issue by DJuego** [maciejkula/spotlight#99]
Hi! Thank you for Spotlight.

I have a similar problem to the issue #80

My OS is Windows 10 x64.

First, i must admit i am new with Anaconda. I have a 'portable' installation Anaconda (with Anaconda3-5.1.0-Windows-x86_64.exe). 

When i try:

conda install -c maciejkula -c pytorch spotlight=0.1.4

i get;
```
u:\Python\Anaconda3>conda install -c maciejkula -c pytorch spotlight=0.1.4
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - spotlight=0.1.4
  - pytorch=0.3.1

Current channels:

  - https://conda.anaconda.org/maciejkula/win-64
  - https://conda.anaconda.org/maciejkula/noarch
  - https://conda.anaconda.org/pytorch/win-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch

u:\Python\Anaconda3>
```
I have not created an environment... Is it necessary?

Perhaps, is it necessary to add channels or so?

**Comment by maciejkula** [comment]
The Windows version requires one more channel: `conda install -c maciejkula -c pytorch -c peterjc123 spotlight=0.1.4`

I've updated the readme in https://github.com/maciejkula/spotlight/pull/98

**Comment by DJuego** [comment]
Thanks, @maciejkula ! It seems work! 👍 At least The examples seem to do their job. :-}

DJuego

**Comment by maciejkula** [comment]
Great!

**Comment by vikrant-sahu** [comment]
does that works with python 2.7, anaconda, win 64
